/* VERSION.H */

// Major version: 01
// Minor version: 00
// Patch Level:   08
// Alpha version: 10

// Version: 1.08a
#define WSANET_VERSION_SEPARATED    1,0,8,10
#define WSANET_VERSION_TEXT         "v1.08alpha\0"

#define WSANET_VERSION_DATE         "December 21th, 1993"

#define WSANET_VERSION 0x0110

#define WSANET_BANNER "WSANET.VBX v1.08alpha \nPublic Domain WinSock NetClient/Ini/NetServer Controls\n(c)1993 Ian Blenke, All Rights Reserved\n"

#define INI_VERSION  0x0110

#define NETSERVER_VERSION 0x0110
